name: Create Release

on:
  workflow_dispatch:
    inputs:
      build-ver:
        description: Build version
        required: true
        default: v0.0.0

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - build
    strategy:
      matrix:
        BUILD_ARCHITECTURE: [x64, x86]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Download Build Artifacts
      uses: actions/download-artifact@v4
      with:
        name: rpc4games-${{ matrix.BUILD_ARCHITECTURE }}
        path: artifact/${{ matrix.BUILD_ARCHITECTURE }}

    - name: Create Release Zips
      run: |
        mkdir -p release/${{ matrix.BUILD_ARCHITECTURE }}/mods
        cp -a external/asi_loader/${{ matrix.BUILD_ARCHITECTURE }}/dinput8.dll release/${{ matrix.BUILD_ARCHITECTURE }}
        cp -a external/discord_sdk/${{ matrix.BUILD_ARCHITECTURE }}/discord_game_sdk.dll release/${{ matrix.BUILD_ARCHITECTURE }}/mods
        cp -a artifact/${{ matrix.BUILD_ARCHITECTURE }}/rpc4games.dll release/${{ matrix.BUILD_ARCHITECTURE }}/mods/rpc4games.dll.asi
        cd release/${{ matrix.BUILD_ARCHITECTURE }}
        zip -r release/rpc4games-${{ github.event.inputs.build-ver }}-${{ matrix.BUILD_ARCHITECTURE }}.zip .

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.build-ver }}
        name: Release ${{ github.event.inputs.build-ver }}
        files: |
          release/rpc4games-${{ github.event.inputs.build-ver }}-x64.zip
          release/rpc4games-${{ github.event.inputs.build-ver }}-x86.zip
        draft: false
        prerelease: false
        make_latest: true
