name: Create Release

on:
  workflow_dispatch:
    inputs:
      build-ver:
        description: Build version
        required: true
        default: v0.0.0

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - build
    strategy:
      matrix:
        BUILD_ARCHITECTURE: [x64, x86]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Download Build Artifacts
      uses: actions/download-artifact@v4
      with:
        workflow: build.yml
        workflow_conclusion: success
        name: rpc4games-${{ matrix.BUILD_ARCHITECTURE }}
        path: release/${{ matrix.BUILD_ARCHITECTURE }}

    - name: Create Release Zips
      run: |
        mkdir -p release/zips
        cd release
        zip -r zips/rpc4games-${{ github.event.inputs.build-ver }}-${{ matrix.BUILD_ARCHITECTURE }}.zip ${{ matrix.BUILD_ARCHITECTURE }}/*.dll

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.build-ver }}
        name: Release ${{ github.event.inputs.build-ver }}
        files: |
          release/zips/rpc4games-${{ github.event.inputs.build-ver }}-x64.zip
          release/zips/rpc4games-${{ github.event.inputs.build-ver }}-x86.zip
        draft: false
        prerelease: false
        make_latest: true
